### ISSUE TITLE
Upgrade???

### ISSUE THREAD

**Issue by PauloBoaventura** [lucasbento/graphql-correios#3]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

S.O = Centos7 - Plesk
Php = 5.6 / 7.0

**Comment by lucasbento** [comment]
@PauloBoaventura: o código roda com NodeJS, caso você queira fazer upgrade de qualquer coisa eu estou aberto à revisar PRs.

O assunto de PHP claramente não pertence à esse projeto.

**Comment by PauloBoaventura** [comment]
@lucasbento 

Bom minha dúvida era se esta implementação estava funcionando.
E o meu problema é colocar um código na plataforma magento 1.9 ou 2.1, que funcione para calculo de frete e que insira o valor deste, no final do pedido.

Se souber algo... Por favor compartilhe!
Abs!

**Comment by lucasbento** [comment]
@PauloBoaventura: sim, ainda funciona, pode [testar aqui](https://graphql-correios-buhpxhxlyr.now.sh/?query=%7B%0A%20%20calcPreco(%0A%20%20%20%20nCdServico%3A%20%2240010%22%2C%0A%20%20%20%20sCepOrigem%3A%20%2211065100%22%2C%0A%20%20%20%20sCepDestino%3A%20%2211721000%22%2C%0A%20%20%20%20nVlPeso%3A%20%220.400%22%2C%0A%20%20%20%20nCdFormato%3A%20%221%22%2C%0A%20%20%20%20nVlComprimento%3A%20%2225%22%2C%0A%20%20%20%20nVlAltura%3A%20%2215%22%2C%0A%20%20%20%20nVlLargura%3A%20%2215%22%2C%0A%20%20%20%20nVlDiametro%3A%20%220%22%0A%20%20)%20%7B%0A%20%20%20%20Codigo%0A%20%20%20%20Valor%0A%20%20%20%20ValorMaoPropria%0A%20%20%20%20ValorAvisoRecebimento%0A%20%20%20%20ValorSemAdicionais%0A%20%20%20%20error%0A%20%20%7D%0A%7D).
